name: 🐞 Bug Report
description: Report a bug or unexpected behavior in PIEE
title: "[BUG] <short description>"
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below so we can fix it faster. ⚡

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: A short summary of the issue.
      placeholder: "Example: Dark mode toggle not persisting after refresh"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce the issue.
      placeholder: |
        1. Go to the homepage
        2. Enable dark mode
        3. Refresh the page
        4. Dark mode is reset to light
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "Dark mode should persist even after refresh."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: "Dark mode resets to light every time I refresh."

  - type: input
    id: environment
    attributes:
      label: Environment Details
      placeholder: "macOS, Chrome 120, PIEE v1.0.3"
      description: Please include OS, browser, and version if possible.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: Add screenshots or screen recordings if relevant.

  - type: textarea
    id: logs
    attributes:
      label: Console Logs or Error Output
      description: Copy and paste any error messages here.
      render: shell

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: "I have searched existing issues to avoid duplicates"
          required: true
